version: '3.3'
services:
  web.student_list:
    image: php:apache
    container_name: web.student_list
    depends_on:
      - api.student_list
    ports:
        - "8090:80"
    volumes:
        - ./website/:/var/www/html
    environment:
        - USERNAME=toto
        - PASSWORD=python
    networks:
      - student_list.network

  api.student_list:
    image: studentlist:v1
    container_name: api.student_list
    volumes:
      - './simple_api/:/data/'
    networks:
      - student_list.network

networks:
  student_list.network: